name: Java Spring CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # -----------------------
  # 1. Build Job
  # -----------------------
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: maven-target
          path: target

  # -----------------------
  # 2. Test Job
  # -----------------------
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run tests
        run: mvn test

  # -----------------------
  # 3. Package Job
  # -----------------------
  package:
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: maven-target
          path: target

      - name: Package JAR
        run: |
          echo "Packaging Spring Boot JAR"
          ls target/*.jar

      - name: Upload packaged JAR
        uses: actions/upload-artifact@v4
        with:
          name: spring-boot-app
          path: target/*.jar

  # -----------------------
  # 4. Deploy Job (Optional)
  # -----------------------
  deploy:
    runs-on: ubuntu-latest
    needs: package
    if: github.ref == 'refs/heads/main' # Only deploy on main branch
    steps:
      - name: Download JAR
        uses: actions/download-artifact@v4
        with:
          name: spring-boot-app
          path: target

      - name: Deploy to server (example)
        run: |
          echo "Deploying Spring Boot App..."
          # Example: scp target/*.jar user@server:/apps/
